### PR TITLE
feat use `dio` and `get_it` set http client; add test and doc

### PR DESCRIPTION
**Pull request by Hu-Wentao**

### CODE REVIEW

**Comment by anasfik** [comment]
Hello, thank you for your work!

can I ask what is the reason/issue is migrating from `http` to `Dio` package?
and why using `get_it`.

I mean what are the situations where it is needed to be, I really respect the effort put in your Pull Request, but I need first to ensure what/why it should be merged.

Thank you, have a great day!

**Comment by Hu-Wentao** [comment]
The reason for using the dio package is because it provides more features and convenience, such as configuring the baseUrl through BaseOptions, adding custom interceptors to implement logging and custom headers, and so on. The custom baseUrl is necessary because the OpenAI API is not available in all regions and may require additional proxy servers. The use of static methods and abstract classes to define constants in the original code is unnecessary when using dio, making development more convenient.

The reason for using get_it is because an application may have multiple dio instances, and if a single global instance is used, conflicts can occur. get_it can help you manage singleton and object instances in the application, avoiding conflicts.

I hope this information is helpful. Thank you for your work on the open-source code repository, and have a great day!

**Comment by anasfik** [comment]
Hello, sorry for the late response, I did try the code with your version which rises `Dio` and `get_it` and honestly it is better to use and to read.

However there is one issue with it is that in case of errors, `DioError` is thrown to the developer with only the status code of the response, as an example a 400 status got to get thrown like this:

image

and this is not good, since as now I designed the library to reflect the error response that is thrown from the OpneAI side which is basically like this:

```json
{
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

```

so that in that Dart application it got thrown as a  with the message from that response:
image



so the developer doesn't get confused by an error of a request that he did without knowing the exact reason of it.
I hope you understand what I tried to say, but at overall your pull request is very helpful and I'm winking to merge it immediately when this issue is fixed.

thank you

**Comment by anasfik** [comment]
hello, is there any updates on this?

**Comment by Hu-Wentao** [comment]
@anasfik Hello! Sorry for the delay in getting back to you. Were you hoping to remove the outermost `on DioError catch (e)`? It's an easy fix, and I'll submit a new version soon.

**Comment by swiecki** [comment]
@Hu-Wentao @anasfik The decision is up to @anasfik but if I understood him correctly he is fine with catching the DioError, but he wants the error message from the response on the DioError, something like this:

`} on DioError catch (e) {
      if (e.response != null) {
        final decodedBody = e.response!.data as Map<String, dynamic>;
        if (decodedBody['error'] != null) {
          final error = decodedBody['error'];
          throw RequestFailedException(
            error["message"],
            e.response!.statusCode,
          );
        }
      } else {
        throw RequestFailedException(
          e.message,
          e.response?.statusCode,
        );
      }
    }`

**Comment by anasfik** [comment]
hello, sorry fir responding late, I will definitely re-check, test it RN.

**Comment by Hu-Wentao** [comment]
@anasfik emm，what can i do for this pr？

**Pull request closed without merging**
