### PR TITLE
Added imageBase64 capability instead of Image URL only for gpt-4-vision

### PR DESCRIPTION
**Pull request by jber18**
Hi @anasfik , I have added capability for image base 64 on OpenAIChatCompletionChoiceMessageContentItemModel instead of URL only for this merge request. 

This functionality will support image from local through base64 encoding.

hope this helps! thank you

### CODE REVIEW

**Comment by jber18** [comment]
> This is a very important feature that's missing and I've just recently been pulling my hair off trying to get it to work. Massive thanks to you mate!

This is a very useful feature for my current app i am working on, Hopefully this feature will be approved by the maintainer.

**Comment by UsamaEjaz0** [comment]
Is this functional?

**Comment by jber18** [comment]
> Is this functional?

Yes, I used this on my current project, where I can simply send a request from an image loaded from local storage

**Review by jber18 — COMMENTED** [review]
imageBase64 from local storage

**Comment by peoplesdriver** [comment]
yes, images from local storage
if (base64Image != null) {
      final base64ImageUrl = "data:image/jpeg;base64,$base64Image";
      chatMessages.add(
        OpenAIChatCompletionChoiceMessageModel(
          role: OpenAIChatMessageRole.user,
          content: [
            OpenAIChatCompletionChoiceMessageContentItemModel.imageUrl(
                base64ImageUrl),
          ],
        ),
      );
    }

**Comment by anasfik** [comment]
Yeah, sorry for not getting into this earlier, will check.

**Review by anasfik — APPROVED** [review]
LGTM, thanks

**Comment by UntitledApps** [comment]
Can you please push the latest version to pub.dev? I need to make use of the newer Open AI Models which are not currently working.

**Comment by sitrucp** [comment]
Local base64 encoded image works using model: "gpt-4-vision-preview" but not model: "gpt-4o" which gives "expected an object, but got a string instead" error.

**Comment by lukepighetti** [comment]
need this pushed to pub!

**Comment by lukepighetti** [comment]
also the image type is hardcoded as `jpeg` but it can also be `png` iirc

**Comment by franboladoruiz** [comment]
I migrated to [`openai_dart` ](https://pub.dev/packages/openai_dart), it seems to be better maintained

**Pull request merged**
