### PR TITLE
display more error details when postStream failed

### PR DESCRIPTION
**Pull request by runtimme**
when use  a deactivated account's api key to createStream 

```dart
    final chatStream = OpenAI.instance.chat.createStream(
      model: "gpt-3.5-turbo",
      temperature: temperature,
      messages: messages,
    );
```

openai backend will return:
```
{
    "message":"",
    "type":"invalid_request_error",
    "param":null,
    "code":"account_deactivated"
}
```

**Note: the message is empty.**

 in this lib, RequestFailedException.message will empty, the developer can only obtain the network request status code :
```dart
                if (doesErrorExists(decodedData)) {
                  final error = decodedData[OpenAIStrings.errorFieldKey]
                      as Map<String, dynamic>;
                  final message = error[OpenAIStrings.messageFieldKey];
                  final statusCode = respond.statusCode;
                  final exception = RequestFailedException(message, statusCode);

                  controller.addError(exception);
                }
```

This PR does the following:

```dart
final message = error[OpenAIStrings.messageFieldKey];
```
change to

```dart
final message = jsonEncode(error);
```

### CODE REVIEW

**Comment by anasfik** [comment]
Thank you for this notice, and yes this is helpful for the developer but is also a breaking change, can we make a conditional expression to check whether the message field is empty or not, if yes then we apply your implementation, otherwise we return directly that message field.

What do you think?

**Comment by runtimme** [comment]
I think it's okay. This is my new commit.

**Comment by runtimme** [comment]
I am a PR novice 😂.If there is anything incorrect here, please guide me. thanks

**Comment by anasfik** [comment]
Thank you

**Pull request merged**
