### PR TITLE
[ Add ] added stream-based chat completion creation for the SDK

### PR DESCRIPTION
**Pull request by K9i-0**
I tried implementing a Chat stream by referring to the code for OpenAI.instance.completion.createStream.

The below is the log of executing the example(chat_campletion_stream_example.dart).
```
OpenAIStreamChatCompletionChoiceMessageModel(role: assistant, content: null)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content: 

)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content: Hi)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content:  there)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content: !)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content:  How)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content:  can)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content:  I)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content:  assist)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content:  you)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content:  today)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content: ?)
OpenAIStreamChatCompletionChoiceMessageModel(role: null, content: null)


Hi there! How can I assist you today?
```

### CODE REVIEW

**Comment by anasfik** [comment]
Hello @K9i-0 

thank you for the contribution, it is really helpful, I will immediately review it.

**Comment by anasfik** [comment]
it looks great and this is exactly what's needed to reflect `Stream` functionality for chat.

Thank you very much @K9i-0  for your contribution and you're welcome if you're interested in implementing more features in the SDK.

**Review by anasfik — APPROVED** [review]

**Comment by anasfik** [comment]
before merging it, there are just some little changes that need to make.
if you have no problem, I can report it to you so you can edit it, otherwise, I will need to edit them by myself.

**Comment by K9i-0** [comment]
I would be happy if you could edit it 👍

**Pull request merged**
